redirects = []

[functions]
included_files = ["/data/**"]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"
pinned_version = "6"

[plugins.inputs]

[build]
publish = "dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"
functions = "netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_build/assets/*"

[headers.values]
cache-control = "public, immutable, max-age=31536000"